# Support Ticket Clustering

In this notebook, we analyze a dataset of support tickets in order to create clusters, which will be assigned to the proper support team.

## Packages

In [3]:
# Data handling
import pandas as pd

## Read and explore dataset

In [6]:
DATASET_PATH = 'dataset/classificacao_atendimento.csv'

tickets_df = pd.read_csv(DATASET_PATH, sep=',', encoding='utf-8')
tickets_df

,ticket_id,subject,body
0,2,Erro na Autocompletação de Código do IntelliJ ...,"Prezado Suporte ao Cliente <name>,\n\nEstou es..."
1,28,Problemas intermitentes de exibição após atual...,"Caro Suporte ao Cliente,\n\n Estou entrando em..."
2,45,Pedido de Assistência para Administração de Se...,"Prezado Suporte ao Cliente de Serviços de TI,\..."
3,46,NaN,"Prezado <name>,\n\nSentimos muito ao saber sob..."
4,63,Urgente: Relato de Falha na Bateria do MacBook...,"Prezado Atendimento ao Cliente,<br><br>Recente..."
...,...,...,...
468,3980,Incidente de alta prioridade,"Caro Time de Suporte ao Cliente,\n\nEspero que..."
469,3983,Urgente: Interrupção de Serviço da AWS,"Caro time de Suporte de Serviços de TI,\n\nEst..."
470,3988,Problema de Cobrança: Cobranças Incorretas na ...,"Caro Equipe de Suporte ao Cliente,\n\nEstou es..."
471,3994,Assistência Necessária para Problema de Tela d...,"Caro Time de Suporte ao Cliente, estou enfrent..."
472,3996,Problemas com a impressora HP DeskJet 3755,"Olá Suporte ao Cliente,\n\nEstou escrevendo pa..."

Check whether the ticket ID column is unique. If yes, convert it to the Dataframe index.

In [8]:
tickets_df["ticket_id"].is_unique

True

The checking above confirms that the ticket_id is unique. Thus, let us convert this column to index.

In [11]:
tickets_df.set_index("ticket_id", inplace=True)
tickets_df

,subject,body
ticket_id,,
2,Erro na Autocompletação de Código do IntelliJ ...,"Prezado Suporte ao Cliente <name>,\n\nEstou es..."
28,Problemas intermitentes de exibição após atual...,"Caro Suporte ao Cliente,\n\n Estou entrando em..."
45,Pedido de Assistência para Administração de Se...,"Prezado Suporte ao Cliente de Serviços de TI,\..."
46,NaN,"Prezado <name>,\n\nSentimos muito ao saber sob..."
63,Urgente: Relato de Falha na Bateria do MacBook...,"Prezado Atendimento ao Cliente,<br><br>Recente..."
...,...,...
3980,Incidente de alta prioridade,"Caro Time de Suporte ao Cliente,\n\nEspero que..."
3983,Urgente: Interrupção de Serviço da AWS,"Caro time de Suporte de Serviços de TI,\n\nEst..."
3988,Problema de Cobrança: Cobranças Incorretas na ...,"Caro Equipe de Suporte ao Cliente,\n\nEstou es..."
3994,Assistência Necessária para Problema de Tela d...,"Caro Time de Suporte ao Cliente, estou enfrent..."
3996,Problemas com a impressora HP DeskJet 3755,"Olá Suporte ao Cliente,\n\nEstou escrevendo pa..."

Basic information

In [12]:
tickets_df.info()

<class 'pandas.DataFrame'>
Index: 473 entries, 2 to 3996
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subject  419 non-null    str
 1   body     473 non-null    str
dtypes: str(2)
memory usage: 11.1 KB

In [13]:
tickets_df.describe()

,subject,body
count,419,473
unique,419,473
top,Erro na Autocompletação de Código do IntelliJ ...,"Prezado Suporte ao Cliente <name>,\n\nEstou es..."
freq,1,1